name: Publicação na Máquina Virtual Linux, na cloud da Azure

on:
  push:
    paths-ignore:
      - backend/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Buildar com npm
        working-directory: ./frontend/
        run: npm install && npm run build

      - name: Copiar os arquivos para a VM via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "frontend/**/*"
          target: "~/PI-3-SEM/"
