name: Deploy do Frontend na Máquina Virtual

on:
  repository_dispatch:
    types: [deploy-frontend]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Parar o serviço pm2 na VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            output=$(pm2 show Sysclub 2>&1) 
            if [[ "$output" != *"[PM2][WARN] Sysclub doesn't exist"* ]]; then
              echo "Parando o serviço Sysclub..."
              sudo pm2 stop Sysclub            
            fi

      - name: Preparar o servidor para novos arquivos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf ~/PI-3-SEM/frontend
            mkdir -p ~/PI-3-SEM/frontend

      - name: Copiar arquivos para a VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "frontend/*"
          target: "~/PI-3-SEM/"

      - name: Buildar e iniciar o serviço na VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/PI-3-SEM/frontend
            echo "Instalando dependências..."
            sudo npm install
            echo "Construindo o projeto..."
            sudo npm run build
            output=$(pm2 show Sysclub 2>&1)
            if [[ "$output" != *"[PM2][WARN] Sysclub doesn't exist"* ]]; then
              echo "Reiniciando o serviço Sysclub..."
              sudo pm2 restart Sysclub
            else
              echo "Iniciando o serviço Sysclub pela primeira vez..."
              sudo pm2 start ecosystem.config.js
            fi
            sudo pm2 save --force
