name: Publicação na Máquina Virtual Linux na Azure

on:
  push:
    paths-ignore:
      - backend/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        working-directory: ./frontend/
        run: npm install

      - name: Buildar o projeto
        working-directory: ./frontend/
        run: npm run build

      - name: Copiar a build para a VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "frontend/.next"
          target: "~/PI-3-SEM/"

      - name: Reiniciar o serviço pi-3-sem-frontend na VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ~/PI-3-SEM/frontend
            pm2 reload all
